name: Code check

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Run TSup (build ESLint preset)
        run: pnpm run build
      - name: Run ESLint
        run: pnpm run lint
  typecheck:
    name: TS Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Run typecheck
        run: pnpm run ts:check